[package]
name = "coniferest"
version = "0.2.1"
edition = "2024"

[lib]
name = "_core"
crate-type = ["cdylib"]

# We'd like to build fast code with `pip install -e '.[dev]'`
[profile.dev]
opt-level = 3

# Makes linking slower, but the resulting extension module is faster
[profile.release]
lto = true
codegen-units = 1

[features]
default = ["pyo3/abi3-py310"]

[dependencies]
itertools = "0.15"
pyo3 = { version = "0.27", features = ["extension-module"] }
# Needs to be consistent with ndarray dependency in numpy
ndarray = { version = "0.17", features = ["rayon"] }
num-traits = "0.2"
numpy = "0.27.1"
# Needs to be consistent with rayon dependency in ndarray
rayon = "1.12"
ordered-float = "5.3.0"
rand = "0.10"
# We use an explicitly specified PRNG algorithm for reproducibility of tree building
rand_xoshiro = "0.8"
